# Generated by Django 5.0 on 2024-01-12 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_rename_variation_cartitem_variations'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='quantily',
            new_name='quantity',
        ),
    ]
