# Generated by Django 5.0.2 on 2024-02-19 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_rename_is_ordered_orderproduct_ordered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderproduct',
            old_name='variations',
            new_name='variation',
        ),
    ]
